// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"math/big"
)

// Defines values for ErrorCode.
const (
	CONFLICT            ErrorCode = "CONFLICT"
	IDEMPOTENCYMISMATCH ErrorCode = "IDEMPOTENCY_MISMATCH"
	INSUFFICIENTFUNDS   ErrorCode = "INSUFFICIENT_FUNDS"
	INTERNAL            ErrorCode = "INTERNAL"
	NOTFOUND            ErrorCode = "NOT_FOUND"
	VALIDATION          ErrorCode = "VALIDATION"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CONFLICT:
		return true
	case IDEMPOTENCYMISMATCH:
		return true
	case INSUFFICIENTFUNDS:
		return true
	case INTERNAL:
		return true
	case NOTFOUND:
		return true
	case VALIDATION:
		return true
	default:
		return false
	}
}

// Defines values for LogType.
const (
	DELETEMETADATA      LogType = "DELETE_METADATA"
	NEWTRANSACTION      LogType = "NEW_TRANSACTION"
	REVERTEDTRANSACTION LogType = "REVERTED_TRANSACTION"
	SETMETADATA         LogType = "SET_METADATA"
)

// Valid indicates whether the value is a known member of the LogType enum.
func (e LogType) Valid() bool {
	switch e {
	case DELETEMETADATA:
		return true
	case NEWTRANSACTION:
		return true
	case REVERTEDTRANSACTION:
		return true
	case SETMETADATA:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	// Address Example: users:alice
	Address string `json:"address"`

	// FirstUsage Earliest effective date this account has been involved in. A backdated transaction can move it earlier.
	FirstUsage    time.Time `json:"firstUsage"`
	InsertionDate time.Time `json:"insertionDate"`

	// Metadata Opaque to the ledger. Never interpreted, only stored.
	Metadata  *Metadata `json:"metadata,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`

	// Volumes Present only when requested with `expand=volumes`.
	Volumes *map[string]Volumes `json:"volumes,omitempty"`
}

// Amount Arbitrary precision integer in the asset's smallest unit. May exceed 2^53.
//
// Example: 10000
type Amount = *big.Int

// Balances Asset to balance. A balance may be negative only for `world`.
//
// Example: {"USD/2":7500}
type Balances map[string]Amount

// CreateTransactionRequest defines model for CreateTransactionRequest.
type CreateTransactionRequest struct {
	// Metadata Opaque to the ledger. Never interpreted, only stored.
	Metadata *Metadata `json:"metadata,omitempty"`
	Postings []Posting `json:"postings"`

	// Reference The caller's own identifier, unique per ledger.
	Reference *string `json:"reference,omitempty"`

	// Timestamp When the movement happened economically, which may be earlier than
	// now. Defaults to now. Stored at microsecond precision.
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable identifier. Branch on this rather than on the message.
	Code ErrorCode `json:"code"`

	// Details Extra context. For INSUFFICIENT_FUNDS this carries the account, asset, available and requested.
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorCode Stable identifier. Branch on this rather than on the message.
type ErrorCode string

// Ledger defines model for Ledger.
type Ledger struct {
	AddedAt time.Time `json:"addedAt"`
	Name    string    `json:"name"`
}

// Log defines model for Log.
type Log struct {
	// Data The mutation, verbatim. These exact bytes are what the hash covers.
	//
	// Passed through untouched rather than re-encoded, because re-encoding
	// would not reproduce the bytes the hash was taken over, and decoding
	// through a generic type would route amounts via float64 and lose
	// precision above 2^53.
	Data json.RawMessage `json:"data"`
	Date time.Time       `json:"date"`

	// Hash SHA-256 over the previous entry's hash and this entry's bytes.
	Hash           []byte  `json:"hash"`
	Id             int64   `json:"id"`
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`
	Type           LogType `json:"type"`
}

// LogType defines model for Log.Type.
type LogType string

// LogPage defines model for LogPage.
type LogPage struct {
	Items []Log   `json:"items"`
	Next  *string `json:"next,omitempty"`
}

// Metadata Opaque to the ledger. Never interpreted, only stored.
type Metadata map[string]string

// Posting defines model for Posting.
type Posting struct {
	// Amount Arbitrary precision integer in the asset's smallest unit. May exceed 2^53.
	//
	// Example: 10000
	Amount Amount `json:"amount"`

	// Asset Carries its own scale. `USD/2` means two decimal places.
	//
	// Example: USD/2
	Asset string `json:"asset"`

	// Destination Example: users:alice
	Destination string `json:"destination"`

	// Source Where the value leaves. `world` for money entering the ledger.
	//
	// Example: world
	Source string `json:"source"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Id int64 `json:"id"`

	// InsertedAt When this database learned of it. May be later than `timestamp`.
	InsertedAt time.Time `json:"insertedAt"`

	// Metadata Opaque to the ledger. Never interpreted, only stored.
	Metadata *Metadata `json:"metadata,omitempty"`

	// PostCommitVolumes Volumes of every touched account immediately after this transaction. Frozen at commit and never rewritten.
	PostCommitVolumes *map[string]map[string]Volumes `json:"postCommitVolumes,omitempty"`
	Postings          []Posting                      `json:"postings"`
	Reference         *string                        `json:"reference,omitempty"`

	// RevertedAt Set when a reversal exists. The reversal is a separate transaction with its own id.
	RevertedAt *time.Time `json:"revertedAt,omitempty"`

	// Timestamp When it happened economically.
	Timestamp time.Time `json:"timestamp"`
}

// TransactionPage defines model for TransactionPage.
type TransactionPage struct {
	Items []Transaction `json:"items"`

	// Next Cursor for the following page. Absent when there is nothing after this one.
	Next *string `json:"next,omitempty"`
}

// Volumes Two counters that only ever increase. Balance is `input - output`.
// Keeping gross flow distinguishes an account that has settled millions
// and now holds nothing from one that was never used.
type Volumes struct {
	// Input Arbitrary precision integer in the asset's smallest unit. May exceed 2^53.
	//
	// Example: 10000
	Input Amount `json:"input"`

	// Output Arbitrary precision integer in the asset's smallest unit. May exceed 2^53.
	//
	// Example: 10000
	Output Amount `json:"output"`
}

// Address defines model for Address.
type Address = string

// Cursor defines model for Cursor.
type Cursor = string

// LedgerPath defines model for LedgerPath.
type LedgerPath = string

// Limit defines model for Limit.
type Limit = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// GetAccountParams defines parameters for GetAccount.
type GetAccountParams struct {
	// Expand Comma separated extras to include. Only `volumes` is supported.
	// Omitted by default because it costs a second query.
	Expand *string `form:"expand,omitempty" json:"expand,omitempty"`
}

// AggregateBalancesParams defines parameters for AggregateBalances.
type AggregateBalancesParams struct {
	// Prefix For example `users:`. Matches on segment boundaries, so `users:` never matches `fees:users:refunds`.
	Prefix *string `form:"prefix,omitempty" json:"prefix,omitempty"`
}

// ListLogsParams defines parameters for ListLogs.
type ListLogsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque position from a previous response. When present every other
	// query parameter is ignored, because the cursor carries the filter it
	// was created with.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	// Account Only transactions where this address is a source or a destination.
	Account *string `form:"account,omitempty" json:"account,omitempty"`

	// AccountPrefix Only transactions touching an account under this prefix, for example `users:`.
	AccountPrefix *string `form:"accountPrefix,omitempty" json:"accountPrefix,omitempty"`
	Reference     *string `form:"reference,omitempty" json:"reference,omitempty"`
	Limit         *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque position from a previous response. When present every other
	// query parameter is ignored, because the cursor carries the filter it
	// was created with.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateTransactionParams defines parameters for CreateTransaction.
type CreateTransactionParams struct {
	// IdempotencyKey Replaying this key returns the original transaction rather than
	// creating a second one.
	//
	// The key is stored with a hash of the request body. Reusing a key
	// with different inputs is an error rather than a silent success for
	// a payment that never happened.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest
